/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EntropyEqualityComparisonInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "compare"
      | "compareWithEntropy"
      | "confidentialProtocolId"
      | "entropyOracle"
      | "entropyRequests"
      | "getEntropyOracle"
      | "initialize"
      | "isInitialized"
      | "requestEntropy"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ComparisonPerformed"
      | "EntropyComparisonPerformed"
      | "EntropyRequested"
      | "ValuesInitialized"
  ): EventFragment;

  encodeFunctionData(functionFragment: "compare", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "compareWithEntropy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entropyRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestEntropy",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "compare", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "compareWithEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entropyRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestEntropy",
    data: BytesLike
  ): Result;
}

export namespace ComparisonPerformedEvent {
  export type InputTuple = [result: BytesLike];
  export type OutputTuple = [result: string];
  export interface OutputObject {
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EntropyComparisonPerformedEvent {
  export type InputTuple = [requestId: BigNumberish, result: BytesLike];
  export type OutputTuple = [requestId: bigint, result: string];
  export interface OutputObject {
    requestId: bigint;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EntropyRequestedEvent {
  export type InputTuple = [requestId: BigNumberish, caller: AddressLike];
  export type OutputTuple = [requestId: bigint, caller: string];
  export interface OutputObject {
    requestId: bigint;
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValuesInitializedEvent {
  export type InputTuple = [initializer: AddressLike];
  export type OutputTuple = [initializer: string];
  export interface OutputObject {
    initializer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EntropyEqualityComparison extends BaseContract {
  connect(runner?: ContractRunner | null): EntropyEqualityComparison;
  waitForDeployment(): Promise<this>;

  interface: EntropyEqualityComparisonInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  compare: TypedContractMethod<[], [string], "nonpayable">;

  compareWithEntropy: TypedContractMethod<
    [requestId: BigNumberish],
    [string],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  entropyOracle: TypedContractMethod<[], [string], "view">;

  entropyRequests: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  getEntropyOracle: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<
    [
      encryptedValue1: BytesLike,
      encryptedValue2: BytesLike,
      inputProof1: BytesLike,
      inputProof2: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  isInitialized: TypedContractMethod<[], [boolean], "view">;

  requestEntropy: TypedContractMethod<[tag: BytesLike], [bigint], "payable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "compare"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "compareWithEntropy"
  ): TypedContractMethod<[requestId: BigNumberish], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "entropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "entropyRequests"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "getEntropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      encryptedValue1: BytesLike,
      encryptedValue2: BytesLike,
      inputProof1: BytesLike,
      inputProof2: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isInitialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "requestEntropy"
  ): TypedContractMethod<[tag: BytesLike], [bigint], "payable">;

  getEvent(
    key: "ComparisonPerformed"
  ): TypedContractEvent<
    ComparisonPerformedEvent.InputTuple,
    ComparisonPerformedEvent.OutputTuple,
    ComparisonPerformedEvent.OutputObject
  >;
  getEvent(
    key: "EntropyComparisonPerformed"
  ): TypedContractEvent<
    EntropyComparisonPerformedEvent.InputTuple,
    EntropyComparisonPerformedEvent.OutputTuple,
    EntropyComparisonPerformedEvent.OutputObject
  >;
  getEvent(
    key: "EntropyRequested"
  ): TypedContractEvent<
    EntropyRequestedEvent.InputTuple,
    EntropyRequestedEvent.OutputTuple,
    EntropyRequestedEvent.OutputObject
  >;
  getEvent(
    key: "ValuesInitialized"
  ): TypedContractEvent<
    ValuesInitializedEvent.InputTuple,
    ValuesInitializedEvent.OutputTuple,
    ValuesInitializedEvent.OutputObject
  >;

  filters: {
    "ComparisonPerformed(bytes32)": TypedContractEvent<
      ComparisonPerformedEvent.InputTuple,
      ComparisonPerformedEvent.OutputTuple,
      ComparisonPerformedEvent.OutputObject
    >;
    ComparisonPerformed: TypedContractEvent<
      ComparisonPerformedEvent.InputTuple,
      ComparisonPerformedEvent.OutputTuple,
      ComparisonPerformedEvent.OutputObject
    >;

    "EntropyComparisonPerformed(uint256,bytes32)": TypedContractEvent<
      EntropyComparisonPerformedEvent.InputTuple,
      EntropyComparisonPerformedEvent.OutputTuple,
      EntropyComparisonPerformedEvent.OutputObject
    >;
    EntropyComparisonPerformed: TypedContractEvent<
      EntropyComparisonPerformedEvent.InputTuple,
      EntropyComparisonPerformedEvent.OutputTuple,
      EntropyComparisonPerformedEvent.OutputObject
    >;

    "EntropyRequested(uint256,address)": TypedContractEvent<
      EntropyRequestedEvent.InputTuple,
      EntropyRequestedEvent.OutputTuple,
      EntropyRequestedEvent.OutputObject
    >;
    EntropyRequested: TypedContractEvent<
      EntropyRequestedEvent.InputTuple,
      EntropyRequestedEvent.OutputTuple,
      EntropyRequestedEvent.OutputObject
    >;

    "ValuesInitialized(address)": TypedContractEvent<
      ValuesInitializedEvent.InputTuple,
      ValuesInitializedEvent.OutputTuple,
      ValuesInitializedEvent.OutputObject
    >;
    ValuesInitialized: TypedContractEvent<
      ValuesInitializedEvent.InputTuple,
      ValuesInitializedEvent.OutputTuple,
      ValuesInitializedEvent.OutputObject
    >;
  };
}
